name: Firebase API Secret

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Firebase API Environment Variables
        run: |
          echo "${{ secrets.API_DATABASE }}" > firebase-key.json
          echo "${{ secrets.API_DATABASE_CONFIG }}" >> config.json

      - name: Verify Environment Variables
        run: |
          echo "Firebase API Key and Config are set."
      - name: Run Django
        run: python manage.py runserver
        env:
          API_DATABASE: firebase-key.json
          API_DATABASE_CONFIG: config.json

        
