name: Firebase API Secret

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set API Firebase Environment Variable
        run: echo "API_DATABASE=${{ secrets.API_DATABASE }}" >> $GITHUB_ENV
